### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by MalditoBarbudo** [emf-creaf/EMFtoolbox#1]
- [x] remove from db and/or content those resources removed from the EMF (to avoid generating them again when building the web)
  - [x] tests for web functions
  - [x] add technical docs section content
  - [x] timers for updating web automatically
  - [x] ~automatic report (resources statistics, resources without updates in last 3 months....)~ Not implemented. We have the matomo statistics for the web. Resources statistics can be extracted at will from the DB if needed.
  - [x] non emf-creaf repositories not updating in `update_all_resources_pages` due to lack of repository info
  - [x] when processing external models and data, try to avoid cloning the same repository (`emf_external_data` or `emf_external_models` for each of them
  - [x] subtitute `usethis::ui*` calls by `cli::cli*` calls
  - [x] add emf-data server functions
  - [x] remove old pipes (`%>%`) and use new R base pipes (`|>`)
